# Lab 02: Manipulate PyTorch Tensors -- solution

In [ ]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [ ]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [ ]:
print( A.size() )
print( A.dim() )
print( A.type() )

torch.Size([2, 2])
2
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [ ]:
A=A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [ ]:
A=torch.rand(5,2,3)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[0.1654, 0.1702, 0.6423],
         [0.9256, 0.4278, 0.7653]],

        [[0.7499, 0.0527, 0.4733],
         [0.0441, 0.1477, 0.4260]],

        [[0.8478, 0.5063, 0.0653],
         [0.4906, 0.5045, 0.5422]],

        [[0.3924, 0.0418, 0.2341],
         [0.1129, 0.3110, 0.2656]],

        [[0.9444, 0.8174, 0.4218],
         [0.2645, 0.3379, 0.3014]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [ ]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
