# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [7]:

# write your code here

A = torch.Tensor([[1, 2], [3, 4]])
print(A)

B = torch.Tensor([[10, 20], [30, 40]])
print(B)

C = A + B
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [9]:

# write your code here

print(A.dim())
print(A.size())
print(A.type())

2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [11]:

# write your code here

A = A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [14]:

# write your code here

R = torch.rand(5, 2, 3)
print(R)
print(R.type())
print(R.dim())
print(R.size())
print(R[1].size())

tensor([[[0.6909, 0.6787, 0.4019],
         [0.6306, 0.3819, 0.4907]],

        [[0.1605, 0.6386, 0.7674],
         [0.1947, 0.4026, 0.9109]],

        [[0.1020, 0.2568, 0.0201],
         [0.5162, 0.8651, 0.3917]],

        [[0.6614, 0.7434, 0.4239],
         [0.7044, 0.0092, 0.1071]],

        [[0.0866, 0.6311, 0.7913],
         [0.1853, 0.9106, 0.3758]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
torch.Size([2, 3])


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [16]:

# write your code here

Z = torch.zeros(2, 3, 4, 5)
print(Z)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
