# Lab 01 : Linear module -- demo

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [3]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.3605, 0.2662, 0.8566, 0.8908, 0.9242])
torch.Size([5])


### Feed it to the module:

In [ ]:
y=mod(x)
print(y)

tensor([-0.7660,  0.1338, -0.1287], grad_fn=<AddBackward0>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [ ]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[-0.2899, -0.2906, -0.3823, -0.0696, -0.0474],
        [-0.4042, -0.2812, -0.0561,  0.2667, -0.1352],
        [-0.2762, -0.2503, -0.3434,  0.4431,  0.2974]], requires_grad=True)
torch.Size([3, 5])


In [ ]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([-0.1514,  0.3378, -0.1148], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [ ]:
with torch.no_grad():
    mod.weight[0,0]=0
    mod.weight[0,1]=1
    mod.weight[0,2]=2
    print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000, -0.0696, -0.0474],
        [-0.4042, -0.2812, -0.0561,  0.2667, -0.1352],
        [-0.2762, -0.2503, -0.3434,  0.4431,  0.2974]], requires_grad=True)


### We can also make a Linear module without bias:

In [ ]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [ ]:
print(mod2.weight)

Parameter containing:
tensor([[-0.4231, -0.1643, -0.2297, -0.2368,  0.0236],
        [ 0.3295,  0.3083, -0.1033,  0.1519, -0.1932],
        [ 0.0089, -0.2818, -0.2800,  0.3098, -0.1770]], requires_grad=True)


In [ ]:
print(mod2.bias)

None
