# Lab 01 : Linear module -- exercise

# Inspecting a linear module

In [2]:
import torch
import torch.nn as nn

### Make a linear module  WITHOUT bias that takes input of size 2 and return output of size 3. 

In [3]:
mod = nn.Linear(2, 3, bias = False)    # complete here
print(mod)

Linear(in_features=2, out_features=3, bias=False)


### Print the internal parameters of the module. Try to print the bias and double check that it return you "None"

In [5]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[-0.1099,  0.0967],
        [ 0.2993,  0.5414],
        [ 0.6666, -0.6603]], requires_grad=True)
None


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to your linear module. What is the output?

In [6]:
x= torch.ones(2) # complete here  
print(x)
y= mod(x) # complete here  
print(y)

tensor([1., 1.])
tensor([-0.0132,  0.8407,  0.0063], grad_fn=<SqueezeBackward3>)


In [8]:
print(mod)
print(mod.weight)
print(mod.bias)

Linear(in_features=2, out_features=3, bias=False)
Parameter containing:
tensor([[-0.1099,  0.0967],
        [ 0.2993,  0.5414],
        [ 0.6666, -0.6603]], requires_grad=True)
None


### Change the internal parameters of your module so that the weights become $
W=\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
$. You need to write 6 lines, one per entry to be changed.

In [9]:
with torch.no_grad():
    mod.weight[0, 0] = 1
    mod.weight[0, 1] = 2
    mod.weight[1, 0] = 3
    mod.weight[1, 1] = 4
    mod.weight[2, 0] = 5
    mod.weight[2, 1] = 6
    # complete here  
    # complete here  
    # complete here  
    # complete here  
    # complete here  
    # complete here  
    print(mod.weight)

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)


### Feed the vector x to your module with updated parameters. What is the output? 

In [10]:
y= mod(x) # complete here  
print(y)

tensor([ 3.,  7., 11.], grad_fn=<SqueezeBackward3>)


### Compute by hand $y=Wx$ and check that pytorch got it correctly. 

$$
\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
\begin{bmatrix}1\\1 \end{bmatrix}=
\begin{bmatrix}?\\? \\ ? \end{bmatrix}
$$