# Lab 01: Introduction to PyTorch  

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.1938, 0.8641],
        [0.3814, 0.1534],
        [0.8393, 0.7462],
        [0.1796, 0.3495],
        [0.7107, 0.9674],
        [0.9613, 0.5830],
        [0.3048, 0.1165],
        [0.2824, 0.4735],
        [0.5903, 0.6947],
        [0.0114, 0.1541]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.8926, 0.5793],
         [0.4328, 0.0521]],

        [[0.0775, 0.5511],
         [0.4169, 0.6157]],

        [[0.9575, 0.3574],
         [0.1479, 0.0358]],

        [[0.5430, 0.2574],
         [0.5045, 0.5773]],

        [[0.8333, 0.5205],
         [0.2211, 0.7538]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

In [9]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [10]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.3707, 0.7461],
         [0.5471, 0.9029]],

        [[0.2851, 0.2655],
         [0.1193, 0.5451]],

        [[0.4178, 0.9266],
         [0.9202, 0.6042]]])


In [11]:
print(  A.dim()   )

3


In [12]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [13]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [ ]:
B=torch.rand(3,5)
print(B)

tensor([[0.3832, 0.9663, 0.1671, 0.2752, 0.4608],
        [0.8758, 0.6267, 0.4151, 0.6652, 0.7178],
        [0.4919, 0.0383, 0.4818, 0.4174, 0.7463]])


In [ ]:
print( B.dim()  )

2


In [ ]:
print( B.size()  )

torch.Size([3, 5])


In [ ]:
print( B.size(0) )

3


In [ ]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [ ]:
x=torch.rand(7)
print(x)

tensor([0.4580, 0.9118, 0.3229, 0.8990, 0.3899, 0.0010, 0.5181])


In [ ]:
print( x.dim() )

1


In [ ]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [19]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(D)
print('')
print(E)

tensor([[0.7503, 0.2465],
        [0.7462, 0.5108]])

tensor([[0.9638, 0.1742],
        [0.3899, 0.7733]])

tensor([[1.9277, 0.3483],
        [0.7798, 1.5466]])

tensor([[2.6779, 0.5948],
        [1.5261, 2.0574]])

tensor([[0.7231, 0.0429],
        [0.2910, 0.3950]])


### Floats versus integers

In [20]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [21]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [22]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [23]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [24]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [27]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([1, 9, 6, 5, 3, 2, 4, 7, 8, 0])
torch.LongTensor


In [26]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [28]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [30]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [31]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [35]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [36]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [37]:
print( y[0] )

tensor([0, 1])


In [38]:
print( y[1] )

tensor([2, 3])


In [39]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [40]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [41]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [42]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [43]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [44]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [45]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [48]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [49]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [51]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
