# Lab 01: Introduction to PyTorch  

In [2]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [3]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [4]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [5]:
A=torch.rand(10,2)
print(A)

tensor([[0.1234, 0.2247],
        [0.8630, 0.8336],
        [0.4954, 0.4846],
        [0.5693, 0.6753],
        [0.1987, 0.3328],
        [0.6268, 0.6737],
        [0.6431, 0.0287],
        [0.6225, 0.9778],
        [0.4315, 0.2466],
        [0.5415, 0.9484]])


### Construct a 10 x 2 matrix filled with zeros

In [6]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [7]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.1306, 0.8695],
         [0.9453, 0.4169]],

        [[0.7062, 0.0383],
         [0.6422, 0.1385]],

        [[0.1260, 0.2292],
         [0.7797, 0.5164]],

        [[0.3230, 0.7873],
         [0.5274, 0.0485]],

        [[0.5727, 0.5666],
         [0.9601, 0.4091]]])


In [8]:
B.size()

torch.Size([5, 2, 2])

In [9]:
B.dim()

3

In [10]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [11]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.5897, 0.8995],
         [0.9585, 0.4300]],

        [[0.1277, 0.5633],
         [0.3988, 0.9857]],

        [[0.9185, 0.0340],
         [0.8665, 0.0765]]])


In [12]:
print(  A.dim()   )

3


In [13]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [14]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [15]:
B=torch.rand(3,5)
print(B)

tensor([[0.8882, 0.9012, 0.4978, 0.4071, 0.8834],
        [0.2301, 0.5704, 0.6121, 0.6094, 0.9309],
        [0.3704, 0.3585, 0.6762, 0.8195, 0.7679]])


In [16]:
print( B.dim()  )

2


In [17]:
print( B.size()  )

torch.Size([3, 5])


In [18]:
print( B.size(0) )

3


In [19]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [20]:
x=torch.rand(7)
print(x)

tensor([0.1021, 0.5220, 0.9717, 0.9110, 0.1921, 0.5791, 0.1482])


In [21]:
print( x.dim() )

1


In [22]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [23]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(D)
print('')
print(E)

tensor([[0.6897, 0.9415],
        [0.1848, 0.8812]])

tensor([[0.3564, 0.0150],
        [0.9958, 0.0383]])

tensor([[0.7127, 0.0299],
        [1.9917, 0.0766]])

tensor([[1.4025, 0.9715],
        [2.1765, 0.9578]])

tensor([[0.2458, 0.0141],
        [0.1840, 0.0338]])


### Floats versus integers

In [24]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [25]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [26]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [27]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [28]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [29]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([2, 1, 8, 7, 4, 0, 9, 5, 3, 6])
torch.LongTensor


In [30]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [31]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [33]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [34]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [35]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [36]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [37]:
print( y[0] )

tensor([0, 1])


In [38]:
print( y[1] )

tensor([2, 3])


In [39]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [40]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [41]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [42]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [43]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [44]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [45]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [48]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [49]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [50]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
