# Lab 03 : Vanilla neural networks -- demo

# Creating a two-layer network

In [1]:
import torch
import torch.nn as nn

### In Pytorch, networks are defined as classes

In [2]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        p = torch.softmax(x, dim=0)
        
        return p

### Create an instance that takes input of size 2, then transform it into something of size 5, then into something of size 3
$$
\begin{bmatrix}
\times \\ \times 
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times \\ \times \\ \times
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times
\end{bmatrix}
$$

In [3]:
net= two_layer_net(2,5,3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [4]:
x=torch.Tensor([1,1])
print(x)

tensor([1., 1.])


In [5]:
p=net.forward(x)
print(p)

tensor([0.3405, 0.2511, 0.4084], grad_fn=<SoftmaxBackward>)


### Syntactic easy for the forward method

In [6]:
p=net(x)
print(p)

tensor([0.3405, 0.2511, 0.4084], grad_fn=<SoftmaxBackward>)


### Let's check that the probability vector indeed sum to 1:

In [7]:
print( p.sum() )

tensor(1.0000, grad_fn=<SumBackward0>)


### This network is composed of two Linear modules that we have called layer1 and layer2. We can see this when we type:

In [8]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [9]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [11]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.2512,  0.1420],
        [-0.5173,  0.3151],
        [ 0.1962, -0.5120],
        [-0.0039, -0.0420],
        [ 0.3137,  0.4086]], requires_grad=True)


In [12]:
 print(net.layer1.bias)

Parameter containing:
tensor([-0.0436,  0.3070,  0.5026, -0.0635,  0.1447], requires_grad=True)


### So to change the first row of the weights from layer 1 you would do:

In [ ]:
with torch.no_grad():
    net.layer1.weight[0,0]=10
    net.layer1.weight[0,1]=20
    print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.0500, -0.5119],
        [-0.1930, -0.1993],
        [-0.0208, -0.0490],
        [ 0.2011, -0.2519]], requires_grad=True)


### Now we are going to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [ ]:
p=net(x)
print(p)

tensor([9.5130e-01, 4.7772e-02, 9.2942e-04], grad_fn=<SoftmaxBackward>)


### Alternatively, all the parameters of the network can be accessed by net.parameters(). 

In [ ]:
list_of_param = list( net.parameters() )
print(list_of_param)

[Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.0500, -0.5119],
        [-0.1930, -0.1993],
        [-0.0208, -0.0490],
        [ 0.2011, -0.2519]], requires_grad=True), Parameter containing:
tensor([ 0.1292, -0.3313, -0.3548, -0.5247,  0.1753], requires_grad=True), Parameter containing:
tensor([[ 0.3178, -0.1838, -0.1930, -0.3816,  0.1850],
        [ 0.2342, -0.2743,  0.2424, -0.3598,  0.3090],
        [ 0.0876, -0.3785,  0.2032, -0.2937,  0.0382]], requires_grad=True), Parameter containing:
tensor([ 0.2120, -0.2751,  0.2351], requires_grad=True)]
