# Lab 03 : Vanilla neural networks -- exercise

# Creating a one-layer network

In [4]:
import torch
import torch.nn as nn

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [5]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        
        # complete here
        self.mylayer = nn.Linear(input_size, output_size)
        
    def forward(self, x):
        
        # complete here
        # complete here
        s = self.mylayer(x)
        
        p = torch.softmax(s, dim = 0)
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [6]:
net= one_layer_net(2, 2) # complete here
print(net)

one_layer_net(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability? Check that it sums to one.

In [8]:
x= torch.ones(2) # complete here
print(x)

# p = net.forward(x)
p = net(x) # complete here
print(p)

print(p.sum() )

tensor([1., 1.])
tensor([0.6281, 0.3719], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [10]:
print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[-0.4473,  0.7004],
        [ 0.1986, -0.3029]], requires_grad=True)
Parameter containing:
tensor([-0.1120, -0.2787], requires_grad=True)


### Change the internal parameters of your network so that the weights are now equal to $
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [ ]:
with torch.no_grad():
    # CHANGE THE WEIGHTS
    # complete here
    # complete here
    # complete here
    # complete here

    # CHANGE THE BIAS
    # complete here
    # complete here

    print(net.mylayer.weight)
    print(net.mylayer.bias)

### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [ ]:
p= # complete here
print(p)