# Lab 03 : Vanilla neural networks -- demo

# Creating a two-layer network

In [2]:
import torch
import torch.nn as nn

### In Pytorch, networks are defined as classes

In [3]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        p = torch.softmax(x, dim=0)
        
        return p

### Create an instance that takes input of size 2, then transform it into something of size 5, then into something of size 3
$$
\begin{bmatrix}
\times \\ \times 
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times \\ \times \\ \times
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times
\end{bmatrix}
$$

In [4]:
net= two_layer_net(2,5,3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [5]:
x=torch.Tensor([1,1])
print(x)

tensor([1., 1.])


In [6]:
p=net.forward(x)
print(p)

tensor([0.2616, 0.4639, 0.2744], grad_fn=<SoftmaxBackward>)


### Syntactic easy for the forward method

In [7]:
p=net(x)
print(p)

tensor([0.2616, 0.4639, 0.2744], grad_fn=<SoftmaxBackward>)


### Let's check that the probability vector indeed sum to 1:

In [8]:
print( p.sum() )

tensor(1., grad_fn=<SumBackward0>)


### This network is composed of two Linear modules that we have called layer1 and layer2. We can see this when we type:

In [9]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [10]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [11]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.0433, -0.0761],
        [ 0.1485, -0.0490],
        [-0.0376, -0.6016],
        [-0.0901,  0.3085],
        [ 0.6438, -0.6161]], requires_grad=True)


In [12]:
 print(net.layer1.bias)

Parameter containing:
tensor([ 0.5111,  0.4378, -0.0100,  0.5958,  0.1648], requires_grad=True)


### So to change the first row of the weights from layer 1 you would do:

In [13]:
with torch.no_grad():
    net.layer1.weight[0,0]=10
    net.layer1.weight[0,1]=20
    print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.1485, -0.0490],
        [-0.0376, -0.6016],
        [-0.0901,  0.3085],
        [ 0.6438, -0.6161]], requires_grad=True)


### Now we are going to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [14]:
p=net(x)
print(p)

tensor([2.7339e-06, 1.0000e+00, 7.4261e-07], grad_fn=<SoftmaxBackward>)


### Alternatively, all the parameters of the network can be accessed by net.parameters(). 

In [15]:
list_of_param = list( net.parameters() )
print(list_of_param)

[Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.1485, -0.0490],
        [-0.0376, -0.6016],
        [-0.0901,  0.3085],
        [ 0.6438, -0.6161]], requires_grad=True), Parameter containing:
tensor([ 0.5111,  0.4378, -0.0100,  0.5958,  0.1648], requires_grad=True), Parameter containing:
tensor([[-0.3220, -0.1148, -0.2681,  0.2941,  0.1721],
        [ 0.0854,  0.1018,  0.1135, -0.0571, -0.1227],
        [-0.3670, -0.2497, -0.4123,  0.2341,  0.3207]], requires_grad=True), Parameter containing:
tensor([-0.1877,  0.4165, -0.0257], requires_grad=True)]


In [17]:
print(net.parameters())

<generator object Module.parameters at 0x7fdf68fbbf50>
